name: diffutil_dart
description: Calculate the difference between two lists as list of edit operations. Used for example for implicitly animating Flutter lists without having to maintain a StatefulWidget.
version: 3.0.0
homepage: https://github.com/knaeckeKami/diffutil.dart

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:


dev_dependencies:
  test: 1.15.0
  lints: ^1.0.1
  test_coverage:

