name: diffutil_dart
description: Calculate the changeset between two lists. Used for implicitly animating Flutter lists without having to maintain a StatefulWidget.
version: 1.0.1
author: Martin Kamleithner
homepage: https://github.com/knaeckeKami/diffutil.dart

environment:
  sdk: ">=2.6.0 <3.0.0"


dependencies:
  meta: ^1.1.0


dev_dependencies:
  test: ^1.15.4
  mockito: ^4.1.2
  test_coverage: ^0.4.3

