name: diffutil_dart
description: Calculate the changeset between two lists. Used for implicitly animating Flutter lists without having to maintain a StatefulWidget.
version: 2.0.0-nullsafety.0
homepage: https://github.com/knaeckeKami/diffutil.dart

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'


dependencies:


dev_dependencies:
  test: ^1.15.4
  mockito: ^4.1.2
  test_coverage: ^0.4.3

